import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Navbar from "@/components/Navbar";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "D@ltex 3.0 ",
  description: "Generated by create next app",
 
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <>
        <SessionAuthProvider>
          {/* <Navbar /> */}
          {children}
          
          </SessionAuthProvider>
        </>
      </body>
    </html>
  );
}