import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import Navbar from "@/components/Navbar";
import { Icon } from "@mui/material";
import Head from "next/head";
import { ThemeProviderWrapper } from "@/context/ThemeContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "D@ltex 3.0 ~ Medical",
  description: "Generated by create next app",
  icons: {
    icon: "/apple.png",  // Ruta del icono
  },
 
 
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       

      <body >
        <>
        <ThemeProviderWrapper>         <SessionAuthProvider>
          {/* <Navbar /> */}
          {children}
          
          </SessionAuthProvider>
          </ThemeProviderWrapper>
 

        </>
      </body>
    </html>
  );
}