name: CI/CD Pipeline for Next.js Application

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Permite ejecución manual desde la interfaz de GitHub

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files
      run: ls -la


    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies # Dependencia del trabajo de instalación
    continue-on-error: true     # Continúa aunque este trabajo falle
    steps:
    - name: Run tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install

    
    - name: Build Next.js application
      run: npm run build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    

      - name: Build Docker image
        run: docker build -t nextjs-app:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name nextjs-app nextjs-app:latest

